### ISSUE TITLE
Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

### ISSUE THREAD

**Issue by aladdin-add** [WebHotelier/webpack-fast-refresh#4]
node: v14.3.0
webpack: 5.0.0-beta.17
@webhotelier/webpack-fast-refresh: 5.0.1 (latest)
react-refresh: 0.8.3(latest)

![image](https://user-images.githubusercontent.com/13050025/84636719-7503f380-af27-11ea-9bce-58fed8a1c885.png)

**Comment by apostolos** [comment]
This looks like a build/misconfiguration error or something weird is going with the way modules are loaded. Can you provide a reduced test case or repo?

**Comment by aladdin-add** [comment]
it was a very large codebase, will try to make a simple repo later.

**Comment by aladdin-add** [comment]
it was fixed by removing `import history form 'history'`.

it works fine in webpack v4, maybe webpack v5 changed something. Anyway I'm going to close the issue, as it's not related to the plugin. Thanks!
